name: Generate Snake Animation

on:
  # Jalankan otomatis setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  # Izinkan untuk menjalankan manual dari tab Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          # Username GitHub kamu
          github_user_name: akuadre
          # Daftar output file SVG yang akan dibuat
          # ?palette=github-dark akan membuat versi tema gelap
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push file SVG yang sudah dibuat ke branch bernama 'output'
      - name: Push GitHub Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          # GITHUB_TOKEN adalah secret bawaan GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
