name: Waka Readme

on:
  schedule:
    - cron: '0 17 * * *'   # Jam 12 malam WIB
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "true"
          LANGS_COUNT: "5"
