name: Waka Readme

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_DAYS_OF_WEEK: "true"
