name: Waka Readme

on:
  # Jalankan setiap hari jam 12 malam
  schedule:
    - cron: '0 0 * * *'
  # Jalankan secara manual jika diperlukan
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_DAYS_OF_WEEK: "false"
          SHOW_PROJECTS: "false"
          LANGS_COUNT: "5"